In [1]:

import sys
import csv
import math
import copy
import time
import numpy as np
from collections import Counter
from numpy import *

## Multiclass classifier decision tree using ID3 algorithm

In [2]:
feature = []

In [21]:
#normalize the entire dataset prior to learning using min-max normalization 
def normalize(matrix):
#     transfer the data metrix to np array in float type.
    print("normalizing the entire dataset:")
    print(a)
    print("Before normalizing")
#     apply the normalization along the 0 axis of a using the formula: (x - x_min)/(x_max - x_min)
    return 


In [22]:
# reading from the file using numpy genfromtxt with delimiter ','
def load_csv(file):
    return (X)

In [23]:
#method to randomly shuffle the array using the numpy.random.shuffle()
def random_numpy_array(ar):
    return arr

In [24]:
#Normalize the data and generate the training labels,training features, test labels and test training
def generate_set(X):
    print(X.shape[0])
#     store the label X[:,-1] to Y

#     reshape y to (Y's length, 1)
#     store it to j

    print("J is",j)
#     create the new_X which exclude the label X[:,:-1]

#     normalize the data step
#     using our implemented function normalize()

#     add the label back to the normiazlied X
#     using np.concatenate along axis=1


#     store the size of rows of the normalized X with labels

#     use the 10% of the data to be the test set.
#     store the number of testing data

#     set the starting idex to be 0

#     set the ending index to be the number of testing data

#     create a list that store all features of the testing data

#     create a list that store all labels of the testing data

#     create a list that store all features of the training data

#     create a list that store all labels of the training data

#     10-fold cross-validation:
    for i in range(10):
#         store the test set for corss-validation using X[start:end,:]

#         get training data before the testing data X[:start, :]

#         get training data after the testing data X[:start, :]

#         form the new training set using np.concatenate

#         get the testing set labels

#         flattent the labels

#         get the training set labels

#         flattent the labels

#         create the test set exclude the labels

#         same for the training set



#         append test data of this fold to the list

#         append test lables of this fold to the list

#         do the same for the training set


#         update the index pointer


#     return the fold list that contain data and label for both training and testing set.
    return 


In [16]:
#build a dictionary where the key is the class label and values are the features which belong to that class.
def build_dict_of_attributes_with_class_values(X,y):
#     init a dict for attributes

#     init feature list.

#     for each feature in the dataset
    for i in range(X.shape[1]):
#         store the featur index

#     find all the value correspond to this feature

#     init an attribute list

#     init the counter to 0

#         for each value in the "all the value correspond to this feature"

#             init a empty list that store the attribute value

#             append the this value to the list

#             append the label of this value to the list

#             append this list to the attribute list.

#             increase the counter

#         add this attribute list to the dict according to the feature index

#         append the feature indx to the feature list.

#     return the dict and feature list.
    return 


In [25]:
# Iterative Dichotomiser 3 entropy calculation
def entropy(y):
#     init a class frequence dict

#     init the attribute entropy to 0

#     for each label in y:
    for i in y:
#         this is label is already in the dict, we increase its feq


#          else, we set the freq to 1


#     calculate the cumulate entropy using the formula.


    return 


In [11]:
#Class node and explanation is self explaination
class Node(object):
#     init the node with val,lchild,rchild,thea and leaf.
    def __init__(self, val, lchild, rchild,thea,leaf):
        self.root_value = val
        self.root_left = lchild
        self.root_right = rchild
        self.theta = thea
        self.leaf = leaf

#     method to identify if the node is leaf
    def is_leaf(self):
        
        return 

#     method to return threshold value
    def ret_thetha(self):
        
        return 
    
#     method return root value
    def ret_root_value(self):
        
        return 
    
#     method return left tree
    def ret_llist(self):
        
        return 

#     method return right tree
    def ret_rlist(self):
        
        return 

    def __repr__(self):
        return "(%r, %r, %r, %r)" %(self.root_value,self.root_left,self.root_right,self.theta)


In [12]:
#Decision tree object
class DecisionTree(object):
#     init a variable called fea_list

#     init the Dtree by setting the root node to None
    def __init__(self):
        self.root_node = None

    #method to return the major class value using Counter() and .most_common()
    def cal_major_class_values(self,class_values):
    
        return 

    #method to calculate best threshold value for each feature
    def cal_best_theta_value(self,ke,attri_list):
#         init a list for data

#         init a list for class labes

#         for each attribute in the attri_list
        for i in attri_list:
#             append the data

#             append the feature value.

#         calculate the entropy of those feaure values

#         init the max info gain = 0

#         init theta=0

#         init a list that store the best index on the left

#         init a list that store the best index on the right

#         init a list that store class labels after split

#         sort the data

#         for each index of data:

#             calculate the current theta using data[i]+data[i+1])/ 2

#             init a list that store index that less than theta

#             init a list that store value that less than theta

#             init a list that store index that greater than theta

#             init a list that store value that less than theta

#             init the counter to 0

#             for each index and value in attri_list
            for c,j in enumerate(attri_list):
#                 if value less or equal than the current theta:

#                     update the "less" list of index and value


#                 else:

#                     update the "greater" list of index and value


#             calculate the entropy of the "less" list

#             calculate the entropy of the "greater" list

#             calculate the info gain using the formular.


#             if current info gain > max info gan

#                 update the info gain, 
#                     the theta, the best index list of right, 
#                         the best index list of left and class_labels_list_after_split





#         return the max info gain, theata,the best left list,the best right list and class label after split
        return 

    #method to select the best feature out of all the features.
    def best_feature(self,dict_rep):
#         set key value to none

#         set best info gain to -1

#         set best theta to 0

#         set best left list to empty

#         set best right list to empty

#         set best class labels after split to empty

#         init a result list

#         for each key in dict_rep:
        for ke in dict_rep.keys():
#             using cal_best_theta_value() and store all returned values

#             if info gian is greater than best info gain:

#                 update info gain, theth, key value,
#                     left list, right list, class labels after split






#         append the key value to the retrun list

#         append the theta value to the retrun list

#         append the left list to the retrun list

#         append the right list to the retrun list

#         append the class labels to the retrun list

#         return the list.
        return 

    def get_remainder_dict(self,dict_of_everything,index_split):
        global fea_list
#         init a split dict

#         for each key "ke" in dict_of_everything:
        for ke in dict_of_everything.keys():
#             init a value list

#             init a modified list

#             get the corresponding values of the key"ke" 

#             for each value and its corresponding index of the key"ke" 

#                 if index is not in the index_split:

#                     append it to the modified list and value list


#             add this modified list to the dict

#         return the splited dict and val list
        return 

    #method to create decision tree
    def create_decision_tree(self, dict_of_everything,class_val,eta_min_val):
        global fea_list
        #if all the class labels are same, then we are set
        if len(set(class_val)) ==1:
            #print("Leaf node for set class is",class_val[0],len(class_val))
            
            return 
        #if the no class vales are less than threshold, we assign the class with max values as the class label    
        elif len(class_val) < eta_min_val:
            
            
            
            return 
#         else:
        else:
#             using the best_feature to get best feature list

#             store the node name, theta,left split, right split and class labes





#             call get_remainder_dict to get left tree data

#             call get_remainder_dict to get right tree data

#             call create_decision_tree to get left tree based on the left tree data

#             call create_decision_tree to get right tree based on therightleft tree data

#             set the root node

#             return root node
            return
            
    #fit the decisin tree
    def fit(self, dict_of_everything,cl_val,features,eta_min_val):
#         set the fea_list the value of features
        global fea_list
    
#         set the root node using the function create_decision_tree()

        return 

    def classify(self,row,root):
#         init the test dict

#         add row to the dict
        for k,j in enumerate(row):
        
#         set the current node to root

#         while the current node is not leaf:
        while not current_node.leaf:
#             implement the case whether the current shoud go to the left


#             implement the case whether the current shoud go to the right

        
#         return the calss of the current node
        return 
        
    #method to the labels for the test data
    def predict(self, X, root):
#         predict using the classify()




        return 

In [26]:
#calculating the predicited accuracy
def accuracy_for_predicted_values(test_class_names1,l):
#     init true and false count to 0

#     for each prediction,if predict is correct then, true++ else, false++
    for i in range(len(test_class_names1)):
       
           
       
        
#     return the acc
    return 

In [13]:
def main(num_arr, eta_min):
    eta_min_val = round(eta_min*num_arr.shape[0])
    #randomly shuffle the array so that we can divide the data into test/training
    
    #divide data into test labels,test features,training labels, training features
    
#     init cumulate acc to 0

    #ten fold iteration 
    for i in range(10):
        #build a dictionary with class labels and respective features values belonging to that class
        
        #instantiate decision tree instance
        
        # build the decision tree model.
        
        #predict the class labels for test features
        
        #calculate the accuracy for the predicted values    
        
#         add acc to cumulate acc

        print("Accuracy is ",accu)
    print("Accuracy across 10-cross validation for",eta_min,"is",float(accu_count)/10)


In [20]:
eta_min_list = [0.05,0.10,0.15,0.20,0.25]
newfile = "..."
num_arr = load_csv(newfile)
for i in eta_min_list:
    main(num_arr,i)

normalizing the entire dataset:
[[6.4 2.7 5.3 1.9]
 [6.3 2.5 4.9 1.5]
 [5.1 3.8 1.9 0.4]
 [5.9 3.  5.1 1.8]
 [6.7 3.3 5.7 2.1]
 [5.7 2.5 5.  2. ]
 [6.3 3.3 4.7 1.6]
 [4.8 3.  1.4 0.3]
 [5.1 3.5 1.4 0.2]
 [5.8 2.8 5.1 2.4]
 [5.7 2.9 4.2 1.3]
 [4.4 2.9 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [6.3 2.7 4.9 1.8]
 [5.6 2.9 3.6 1.3]
 [5.6 2.8 4.9 2. ]
 [6.5 3.  5.8 2.2]
 [5.7 2.8 4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [5.1 3.5 1.4 0.3]
 [5.6 2.5 3.9 1.1]
 [6.3 2.8 5.1 1.5]
 [6.3 3.3 6.  2.5]
 [7.7 3.8 6.7 2.2]
 [5.6 3.  4.1 1.3]
 [5.  3.5 1.6 0.6]
 [5.2 2.7 3.9 1.4]
 [6.2 2.9 4.3 1.3]
 [6.8 3.  5.5 2.1]
 [5.9 3.  4.2 1.5]
 [6.7 3.  5.  1.7]
 [4.8 3.  1.4 0.1]
 [7.7 2.6 6.9 2.3]
 [4.5 2.3 1.3 0.3]
 [4.7 3.2 1.3 0.2]
 [5.4 3.  4.5 1.5]
 [4.4 3.  1.3 0.2]
 [7.7 3.  6.1 2.3]
 [6.  3.  4.8 1.8]
 [5.4 3.4 1.5 0.4]
 [5.5 2.4 3.8 1.1]
 [6.  2.7 5.1 1.6]
 [5.1 2.5 3.  1.1]
 [5.1 3.4 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [6.9 3.1 4.9 1.5]
 [6.3 2.5 5.  1.9]
 [4.6 3.2 1.4 0.2]
 [6.3 2.3 4.4 1.3]
 [6.3 2.9 5.6 1.8]
 [4.9 3.1 1.5 0.1]

Accuracy is  0.9333333333333333
Accuracy is  0.9333333333333333
Accuracy is  1.0
Accuracy is  0.9333333333333333
Accuracy is  0.8666666666666667
Accuracy is  1.0
Accuracy is  1.0
Accuracy is  0.9333333333333333
Accuracy is  0.9333333333333333
Accuracy is  0.9333333333333333
Accuracy across 10-cross validation for 0.15 is 0.9466666666666667
normalizing the entire dataset:
[[6.3 3.4 5.6 2.4]
 [4.9 2.5 4.5 1.7]
 [5.5 2.4 3.8 1.1]
 [5.4 3.9 1.3 0.4]
 [7.2 3.  5.8 1.6]
 [4.9 3.1 1.5 0.1]
 [5.4 3.4 1.5 0.4]
 [5.  3.2 1.2 0.2]
 [5.1 3.7 1.5 0.4]
 [5.7 2.5 5.  2. ]
 [6.1 3.  4.9 1.8]
 [6.5 3.  5.8 2.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.9 3.6 1.3]
 [6.2 2.2 4.5 1.5]
 [6.  3.4 4.5 1.6]
 [4.7 3.2 1.6 0.2]
 [6.4 3.1 5.5 1.8]
 [6.8 3.  5.5 2.1]
 [5.8 2.7 4.1 1. ]
 [5.2 2.7 3.9 1.4]
 [6.3 2.7 4.9 1.8]
 [6.5 3.  5.2 2. ]
 [4.5 2.3 1.3 0.3]
 [6.  2.9 4.5 1.5]
 [7.9 3.8 6.4 2. ]
 [6.6 2.9 4.6 1.3]
 [5.8 4.  1.2 0.2]
 [6.3 2.3 4.4 1.3]
 [7.2 3.6 6.1 2.5]
 [6.3 3.3 6.  2.5]
 [6.4 2.9 4.3 1.3]
 [4.4 3.  1.3 0.2]